### ISSUE TITLE
Saving to /tmp

### ISSUE THREAD

**Issue by PLBMR** [vyzyv/vimpyter#10]
Every time I try to `:w` when editing a `.ipynb` file now, it saves my notebook to the `/tmp` directory rather than to the current directory. Is there something within this package that is setting where the notebook is saved?

**Comment by vyzyv** [comment]
Change global variable to ```g:vimpyter_view_directory```, for example: ```let g:vimpyter_view_directory = '$HOME/.vimpyter_views'```.

Take note, that the view (.ipynb opened in vim) is only in /tmp (or should be) and everytime you save your notebook results are converted to your original notebook in your specified directory. Are your notebooks saved correctly in this manner?
