### ISSUE TITLE
fails to load notebooks with spaces in name

### ISSUE THREAD

**Issue by jwkvam** [vyzyv/vimpyter#5]
This looks really handy! I often have spaces in my notebook filenames and it seems like that breaks something. It just loads up an empty buffer when I try.

**Comment by vyzyv** [comment]
Confirm whether it's working now, cheers!

**Comment by jwkvam** [comment]
Looks good to me thanks!

**Comment by mrquincle** [comment]
Ah, that's why it didn't work!!

```uname -a
Linux V 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux```

```notedown --version
1.5.1```

I installed `vimpyter` via Vundle. I can't find the version via `:help vimpyter-options`. Do I have a version that is too old? How do I found out?

**Comment by szymonmaszke** [comment]
Just update the plugin using `:PluginUpdate` and you should be fine. You can clone this repository and compare commits with the one located in Vundle, close if everything is fine.

**Comment by mrquincle** [comment]
Ah, I only now discovered that Vundle is actually cloning your repository under the hood, neat. https://github.com/szymonmaszke/vimpyter.git. It's up to date with origin/master. So, that means there must still be some bugs somewhere. Can I somehow get you a log?

**Comment by szymonmaszke** [comment]
Give me more details about your issues. Filename, does this plugin work for you at all? Vim/Neovim version, preferably directory where your `.ipynb` is located, anything you think could be related.

**Comment by mrquincle** [comment]
This patch fixes it. For any file with spaces in the name, for example "Keras Adversarial Autoencoder.ipynb" only $TMPDIR/Keras will be created and become empty. I narrowed it down to the system call to notedown where the target file apparently needs quotes. There might be other files that actually need quotes as well, but this already fixes it on my system.
