### ISSUE TITLE
Empty notebook on neovim

### ISSUE THREAD

**Issue by prdx** [vyzyv/vimpyter#7]
Hi,

I am trying to open my notebook but it shows nothing on neovim that uses vimpyter. However, I am not sure how to debug it any further. I can open the notebook on browser or see the content if vimpyter is not used and this happens only in one specific file.

I like this plugin and I would love to help debugging it from my side. Please let me know if you need further information or have a clue where should I start debugging it.

Thank you.

**Comment by vyzyv** [comment]
Upload your notebook (if possible) and I'll see what I can do. How big is it and what type of content does it hold? What's the name of your notebook (I suspect it could be the issue).

If you want to debug it on your own you should start from the function ```vimpyter#createView()``` in ```autoload/vimpyter.vim```

**Comment by prdx** [comment]
@vyzyv sorry for the late reply. I cannot upload the file here (github does not allow me), so I will email you the file if that is ok?

**Comment by vyzyv** [comment]
Go ahead, you can find it on my profile.

**Comment by vyzyv** [comment]
Would be glad if you could confirm it's working fine with the newest update.
