### ISSUE TITLE
On-demand loading of plugins by vim-plug

### ISSUE THREAD

**Issue by maamo888** [vyzyv/vimpyter#8]
I am using a plugin manager called vim-plug.

If filetype is ipynb only, it can not be a way such as to load the vimpyter.

https://github.com/junegunn/vim-plug#on-demand-loading-of-plugins

**.vimrc**

```vimrc
Plug 'vyzyv/vimpyter', { 'for': ['ipynb'] }
```

**Comment by vyzyv** [comment]
Will look into lazy loading of plugins, thanks for pointing that out.

**Comment by maamo888** [comment]
Thank you for reply.

I am waiting for correction and change.

Additional report.

```vim
Plug 'jmcantrell/vim-virtualenv', { 'for': ['python', 'djangohtml', 'htmljinja', 'ipynb'] }
Plug 'davidhalter/jedi-vim', { 'for': ['python', 'ipynb'], 'do': 'git submodule update --init' }
Plug 'Vimjas/vim-python-pep8-indent', { 'for': ['python', 'ipynb'] }
Plug 'heavenshell/vim-pydocstring', { 'for': ['python', 'ipynb'] }
```

**Comment by vyzyv** [comment]
This plugin is already loaded only on .ipynb files.
It is really small and rather fast (check your vim startup time and this plugin's contribution to it).

I don't think it's worth the effort honestly, but if you wish you can implement it and I'll happily merge your PR.

What about additional report? Is jedi-vim working for you with .ipynb files? I can't make it work that way.
